language: node_js
node_js:
  - '7'
  - '6'
before_install:
  - npm set progress=false
  - npm config ls
script: npm test
after_success:
  - npm cover
  - './node_modules/.bin/coveralls < ./coverage/lcov.info'
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info
cache:
  directories:
  - node_modules